logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    initialSize: 5
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    removeAbandoned: true
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/covr-prod}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: "true"
